"""drop asset barcode

Revision ID: 3b95b648b392
Revises: ffcdc082246c
Create Date: 2026-08-27 20:48:58.843933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b95b648b392'
down_revision: Union[str, Sequence[str], None] = 'ffcdc082246c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """撤掉 Code 128-C 标签方案留下的条码字段。

    ffcdc082246c 已经发布过,服务器可能已经执行了它 —— 所以不能删那个迁移文件,
    只能往前加一步把列去掉。这样「已升级过的老库」和「全新的库」最终都落到
    同一个结构上。

    列里的数据(回填的 6 位条码号)会一并丢掉。方案已经放弃,不再需要。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_barcode'))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_barcode'), ['barcode'], unique=1)

    # ### end Alembic commands ###
