"""baseline

Revision ID: f7c481d81810
Revises: 
Create Date: 2026-08-27 01:56:37.734825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c481d81810'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tag_prefix', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag_prefix')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('serial_no', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'REPAIR', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_tag'), ['asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_serial_no'), ['serial_no'], unique=False)

    op.create_table('checkout_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('checkin_operator_id', sa.Integer(), nullable=True),
    sa.Column('kit_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['checkin_operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkout_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkout_records_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_active_checkout_per_asset', ['asset_id'], unique=True, sqlite_where=sa.text('checked_in_at IS NULL'))

    op.create_table('inventory_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('checked_by_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('observed_location', sa.String(length=128), nullable=False),
    sa.Column('observed_status', sa.Enum('IN_STOCK', 'REPAIR', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('location_at_check', sa.String(length=128), nullable=False),
    sa.Column('status_at_check', sa.Enum('IN_STOCK', 'REPAIR', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_checks_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_checks_checked_at'), ['checked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_checks_checked_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_checks_asset_id'))

    op.drop_table('inventory_checks')
    with op.batch_alter_table('checkout_records', schema=None) as batch_op:
        batch_op.drop_index('uq_active_checkout_per_asset', sqlite_where=sa.text('checked_in_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_checkout_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_records_asset_id'))

    op.drop_table('checkout_records')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_serial_no'))
        batch_op.drop_index(batch_op.f('ix_assets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_tag'))

    op.drop_table('assets')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
