"""asset barcode

Revision ID: ffcdc082246c
Revises: 50a5d6cbf7a1
Create Date: 2026-08-27 20:20:42.472145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcdc082246c'
down_revision: Union[str, Sequence[str], None] = '50a5d6cbf7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=6), nullable=True))

    # 回填:已有设备也要有条码号,否则它们的标签打不出来。
    # 规则与新建时一致(app/services.create_asset_with_tag):主键补零到 6 位。
    # autogenerate 不会写这一步 —— 它只比对结构,不管数据。
    op.execute("UPDATE assets SET barcode = printf('%06d', id) WHERE barcode IS NULL")

    # 唯一索引放在回填之后建:先建的话,回填过程中会撞上一堆 NULL 之外的重复判定
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_barcode'), ['barcode'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_barcode'))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
